# Generated by Django 3.2.4 on 2021-06-20 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognizer', '0002_alter_personimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
