# Generated by Django 3.2.4 on 2021-06-29 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recognizer', '0004_alter_personimage_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='personimage',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recognizer.person'),
        ),
    ]
