# Generated by Django 3.2.4 on 2021-06-28 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recognizer', '0003_person_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personimage',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recognizer.person'),
        ),
    ]
