# Generated by Django 3.2.4 on 2021-06-20 22:14

from django.db import migrations, models
import recognizer.models


class Migration(migrations.Migration):

    dependencies = [
        ('recognizer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personimage',
            name='image',
            field=models.ImageField(upload_to=recognizer.models.upload),
        ),
    ]
